- name: ensure sssd packages are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - sssd
    - sssd-tools

- name: update /etc/sssd/sssd.conf from template
  template:
    src: etc/sssd/sssd.conf
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - restart sssd

- name: ensure that sss user exists in ldap
  ldap:
    bind_dn: cn=admin,{{ ldap_auth_base_dn }}
    bind_password: "{{ ldap_auth_admin_password }}"
    entry_dn: uid=sss,ou=services,{{ ldap_auth_base_dn }}
    attributes:
      - objectClass: account
      - objectClass: simpleSecurityObject
      - uid: sss
      - userPassword: "{{ sssd_ldap_password|ssha_password_hash(sssd_ldap_password_salt) }}"
    modify_action: replace
    state: present
  notify:
    - restart sssd

- name: ensure mkhomedir module is present in /etc/pam.d/common-session iff enabled
  lineinfile:
    dest: /etc/pam.d/{{ item }}
    line: session required pam_mkhomedir.so umask=0022 skel=/etc/skel
    regexp: ^session\s+required\s+pam_mkhomedir.so.*$
    insertbefore: ^session\s+required\s+pam_unix.so.*$
    state: "{{ 'present' if sssd_enable_mkhomedir else 'absent' }}"
  with_items:
    - common-session
    - common-session-noninteractive 

- name: ensure that hostname is set in /etc/hosts if desired...
  lineinfile:
    dest: /etc/hosts
    regexp: ^127.0.0.1\s+localhost
    line: 127.0.0.1 localhost {{ ansible_hostname }}
    state: present
  when: sssd_enable_modify_hosts

- name: ensure sssd services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - sssd
