- name: ensure required base packages are present
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - sssd

- name: update /etc/sssd/sssd.conf from template
  template:
    src: etc/sssd/sssd.conf
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600

# delete from pam if not enabled?
