- name: ensure required base packages are present
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - libnss-ldap
    - libpam-ldap

- name: update /etc/ldap.conf from template
  template:
    src: etc/ldap.conf
    dest: /etc/ldap.conf
    owner: root
    group: root
    mode: 0644
 
- name: configure nss to use ldap
  command: auth-client-config -t nss -p lac_ldap

- name: configure pam to use ldap
  when: ldap_enable_login

- name: configure pam to use ldap
  when: ldap_enable_mkhomedir
